# Numpy
Numpy bilimsel hesaplamalar için Python'ın temel kütüphanesidir. Büyük boyutlu dizi ve matrisleri destekler ve yüksek seviye matematiksel fonksiyonları bunlar üzerinde işletebilir.

In [0]:
import numpy as np

numpy as np yazdıktan sonra numpy'ı kısaca np olarak kullanabiliriz.

## Numpy Arrays
Bir Numpy dizisi oluşturulurken np.array() dizimi kullanılır.

In [11]:
# 5 elemanlı bir vektör
a = np.array([1,2,3,4,5])
print(a)
#2 boyutlu bir dizi
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


### Bir Dizi Başlatma
Numpy ile tamamen 0 veya tamamen 1'lerden oluşan, alt üst sınır ve aralık belirleyebileceğimiz özel diziler, rastgele değerlerden oluşan, n boyutlu birim matris gibi çeşitli diziler tek satırla oluşturulabilinir.

**Zeros matrisi oluşturma**

In [3]:
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Ones matrisi oluşturma**

In [12]:
o = np.ones((3,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Eşit aralıklı matris oluşturma**
np.arange(min,max,adım) şeklinde girilir. Burada üst sınır olarak girilen sayı dahil değildir.

In [17]:
n = np.arange(5,106,20)
print(n)

[  5  25  45  65  85 105]


**Belirli aralığı eşit parçaya bölen vektörü oluşturma** np.linspace(min,max,örneksayısı)

In [19]:
w = np.linspace(0.5,2,5)
print(w)

[0.5   0.875 1.25  1.625 2.   ]


**NxM boyutlu sabit sayı dizisi oluşturma**

In [23]:
e = np.full((3,3),5)
print(e)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


**NxN boyutunda birim matris oluşturma**

In [24]:
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Rastgele değerler matrisi oluşturma (0-1 arasında)**

In [27]:
r1 = np.random.random((3,4))
print(r1)

[[0.81307083 0.58060778 0.50290036 0.72594285]
 [0.21376038 0.08804649 0.43992275 0.29560351]
 [0.37013476 0.30547292 0.52806921 0.76189612]]


**Rastgele değerler matrisi oluşturma (Aralık belirleyerek)** Alt değer dahildir, üst deer dahil değildir. np.random.randint(min,max,(boyut x boyut))

In [29]:
r2 = np.random.randint(1,20,(5,5))
print(r2)


[[19  7  3  6 13]
 [ 7 18  8 12  4]
 [ 9 11  3 15 18]
 [10 18 10 11 14]
 [ 9  7  9  9  9]]
[18  9 15 17 15  5 11 25 10 23]


Sadece üst sınır ve boyut belirleyerek aşağıdaki gibi de oluşturulabilir. Alt sınır 0 olur.

In [30]:
r3 = np.random.randint(50, size=(10))
print(r3)

[19 17 37 34 49 29  6 13 29 45]


## Dizi Özelliklerini Kontrol Etme

**Dizi boyutununu bulma**

In [32]:
r2.shape

(5, 5)

In [33]:
r3.shape

(10,)

**Dizi uzunluğunu bulma**

In [34]:
len(r3)

10

**Dizi boyut sayısını bulma**

In [37]:
i.ndim

2

**Dizi eleman sayısını bulma**

In [38]:
i.size

16

**Dizi elemanlarının veri tipini bulma**

In [39]:
i.dtype

dtype('float64')

In [40]:
i.dtype.name

'float64'

**Dizinin türünü değiştirme**

In [41]:
i.astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## Aritmetik İşlemler

Numpy'ın temel kütüphanelerden birisi olmasındaki en büyük sebep matematiksel işlemlerde kolaylık sağlamasıdır. Özellikle dizi işlemlerinde çok kullanışlı fonksiyonlara sahiptir.

In [65]:
x = np.full((5,5),5)
print(x)
y = np.zeros ((5,5))
print(y)
z = np.ones((5,5))
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Toplama**

In [50]:
np.add(x,z)

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

**Çıkarma**

In [51]:
np.subtract(y,x) # y-x

array([[-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.]])

**Çarpma**

In [67]:
np.multiply(x,2*z)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

**Bölme**

In [69]:
np.divide(x,2*z)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

**Eksponansiyel**

In [70]:
np.exp(z) # z vektörü elemanlarını e sayısının kuvveti olarak alır.

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183]])

**Karekökünü alma**

In [71]:
np.sqrt(x)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798]])

**Doğal Logaritma**

In [75]:
np.log(x)

array([[1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791]])

**Trigonometrik işlemler**

In [77]:
np.sin(x)

array([[-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427],
       [-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427],
       [-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427],
       [-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427],
       [-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427]])

In [78]:
np.cos(y)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Fonksiyonlar

**Dizi elemanlarını toplama**

In [79]:
x.sum()

125

**Minimum değeri bulma**

In [80]:
t = np.random.randint(10,60,5)
print(t)

[41 42 15 55 45]


In [81]:
t.min()

15

**Maksimum değeri bulma**

In [82]:
t.max()

55

**Ortalama değeri bulma**

In [87]:
t.mean()

39.6

**Dizi elemanlarını sıralama**

In [89]:
t.sort()
print(t)

[15 41 42 45 55]


## Subsetting, Slicing, Indexing

Listelerde de kullanılan, dizi içinden belli bir elemanın alınması, dizinin satır sütunlarının bir kısmının kesilmesi veya bir şartı sağlayan elemanların seçilmesi gibi işlemler yapılabilir.

In [91]:
p = 10*np.random.random((4,3))
print(p)

[[7.71651561 5.33793857 7.60059837]
 [0.01222373 3.04653252 6.03236162]
 [5.9859997  4.36967264 4.93112821]
 [4.80846228 6.31379851 0.57127202]]


### Subsetting

In [95]:
p[0,0]

7.716515605579705

In [96]:
p[2,1]

4.369672642622709

### Slicing

Burada girilen sınırlar exclusivedir. Yani girilen satır sütun değerleri dahil değildir.

In [98]:
p[:2,:2] # 2.satır ve 2.sütuna kadar olan alt matris

array([[7.71651561, 5.33793857],
       [0.01222373, 3.04653252]])

In [99]:
p[1,:] # 1 indeksli satır ve tüm sütunlar

array([0.01222373, 3.04653252, 6.03236162])

In [100]:
p[1,-1] # 1 indeksli satırın sondan 1.elemanı

6.032361620431503

### Boolean Indexing

In [101]:
p[p<5] # p'nin 5'ten küçük elemanlarının vektörü

array([0.01222373, 3.04653252, 4.36967264, 4.93112821, 4.80846228,
       0.57127202])

## Dizi Yönlendirme

### Transpoz

In [102]:
 pt = np.transpose(p)
 print(pt)

[[7.71651561 0.01222373 5.9859997  4.80846228]
 [5.33793857 3.04653252 4.36967264 6.31379851]
 [7.60059837 6.03236162 4.93112821 0.57127202]]


In [103]:
p.T

array([[7.71651561, 0.01222373, 5.9859997 , 4.80846228],
       [5.33793857, 3.04653252, 4.36967264, 6.31379851],
       [7.60059837, 6.03236162, 4.93112821, 0.57127202]])

### Dizi Şeklini Değiştirme

**1 boyutlu hale getirme (Flatten)**

In [104]:
p.ravel()

array([7.71651561, 5.33793857, 7.60059837, 0.01222373, 3.04653252,
       6.03236162, 5.9859997 , 4.36967264, 4.93112821, 4.80846228,
       6.31379851, 0.57127202])

**Şeklini değiştirme (asıl diziyi değiştirmez)**

In [108]:
p.reshape(6,2)

array([[7.71651561, 5.33793857],
       [7.60059837, 0.01222373],
       [3.04653252, 6.03236162],
       [5.9859997 , 4.36967264],
       [4.93112821, 4.80846228],
       [6.31379851, 0.57127202]])

### Eleman Ekleme/Çıkarma

**Şeklini değiştirme (asıl diziyi etkiler)**

In [111]:
p.resize(6,2)
print(p)

[[7.71651561 5.33793857]
 [7.60059837 0.01222373]
 [3.04653252 6.03236162]
 [5.9859997  4.36967264]
 [4.93112821 4.80846228]
 [6.31379851 0.57127202]]


**Diziye eleman ekleme**

In [118]:
np.append(p,p) # 24 elemanlı vektör haline geldi.

array([7.71651561, 5.33793857, 7.60059837, 0.01222373, 3.04653252,
       6.03236162, 5.9859997 , 4.36967264, 4.93112821, 4.80846228,
       6.31379851, 0.57127202, 7.71651561, 5.33793857, 7.60059837,
       0.01222373, 3.04653252, 6.03236162, 5.9859997 , 4.36967264,
       4.93112821, 4.80846228, 6.31379851, 0.57127202])

In [119]:
np.shape(np.append(p,p))  

(24,)

**Belirli bir konuma eleman ekleme**

In [130]:
r = np.ravel(p)
print(r)

[7.71651561 5.33793857 7.60059837 0.01222373 3.04653252 6.03236162
 5.9859997  4.36967264 4.93112821 4.80846228 6.31379851 0.57127202]


In [131]:
np.insert(r,1,5) # 1 indeksli eleman 5 olacak şekilde eleman ekledik. Asıl diziyi etkilemez.

array([7.71651561, 5.        , 5.33793857, 7.60059837, 0.01222373,
       3.04653252, 6.03236162, 5.9859997 , 4.36967264, 4.93112821,
       4.80846228, 6.31379851, 0.57127202])

**Diziden eleman silme**

In [132]:
np.delete(r,0) # 0 indeksli eleman silindi. Asıl diziyi etkilemez.

array([5.33793857, 7.60059837, 0.01222373, 3.04653252, 6.03236162,
       5.9859997 , 4.36967264, 4.93112821, 4.80846228, 6.31379851,
       0.57127202])

### Dizileri Kombinleme

**Elemanları yuvarlamak**

In [143]:
r = np.round(r)
print(r)

[8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]


**Dizileri Bağlamak**

In [144]:
np.concatenate((r,r)) # 2 diziyi yan yana ekledi.

array([8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1., 8., 5., 8., 0., 3.,
       6., 6., 4., 5., 5., 6., 1.])

**Dizileri yatay olarak yığma (Satırlar üst üste gelir)**

In [149]:
q = np.vstack((r,r))
print(q)

[[8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]]


**Dizileri dikey olarak yığma**

In [147]:
np.hstack((r,r))

array([8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1., 8., 5., 8., 0., 3.,
       6., 6., 4., 5., 5., 6., 1.])

### Dizileri Ayırma

**Dikey olaray belirli bir konumda ayırma**

In [150]:
np.hsplit(r,4) # 4.indeksten itibaren ayırdı.

[array([8., 5., 8.]),
 array([0., 3., 6.]),
 array([6., 4., 5.]),
 array([5., 6., 1.])]

**Yatay olarak belirli bir konumdan ayırma**

En az 2 boyutlu dizilerde yapılabilir. Bunun için yeni dizi oluşturuyorum.

In [157]:
q = np.vstack((q,q))
print(q)

[[8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]
 [8. 5. 8. 0. 3. 6. 6. 4. 5. 5. 6. 1.]]


In [160]:
np.vsplit(q,2)

[array([[8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.]]),
 array([[8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.],
        [8., 5., 8., 0., 3., 6., 6., 4., 5., 5., 6., 1.]])]